### ISSUE TITLE
yamerl (or fakerl) application not started with make shell

### ISSUE THREAD

**Issue by bunnylushington** [rpip/fakerl#1]
Hi -- Small issue: Running `make shell` and `fakerl:fetch("jobs..jobs').` as you suggest results in the following error:

```
Eshell V6.4  (abort with ^G)
1> fakerl:fetch("jobs.jobs").
** exception error: no match of right hand side value undefined
     in function  yamerl_app:get_param/1 (src/yamerl_app.erl, line 66)
     in call from yamerl_constr:setup_node_mods/1 (src/yamerl_constr.erl, line 449)
     in call from yamerl_constr:initialize/1 (src/yamerl_constr.erl, line 519)
     in call from yamerl_constr:file/2 (src/yamerl_constr.erl, line 227)
     in call from fakerl:get_locale_data/1 (src/fakerl.erl, line 177)
     in call from fakerl:fetch/2 (src/fakerl.erl, line 161)
     in call from fakerl:fetch/1 (src/fakerl.erl, line 134)
```

Because yamerl hasn't been started.  `application:start(fakerl).` fixes that right up.  Not sure if it's a Makefile or a documentation issue.  Anyhow, thanks for releasing the library, it's hugely useful!

**Comment by rpip** [comment]
Thanks! I haven't touched this in a while, but I have just pushed the fix; starts the fakerl application when starting the Erlang shell
